### ISSUE TITLE
Still issues with upstream problem

### ISSUE THREAD

**Issue by eboateng** [quaquel/epa1361_open#9]
Noticed there are some issues with the upstream problem since the last commit/push. Certain outcomes are outcomes are summed up with no option to individually analyse them. Could you please check this? Perhaps I may be mistaken in judgement.

**Comment by quaquel** [comment]
Can you be a lot clearer and give me an example. I have no idea what you mean.

**Comment by eboateng** [comment]
so in the previous model, the Evaluator with scenarios and policies gave out all the individual outcomes with prefix A_X. Now it seems only gives out an aggregate of each outcome for instance Expected number of deaths.

**Comment by quaquel** [comment]
Again, not clear. There are various examples of how to use the model for the final assignment. Which one are you referring to?

**Comment by eboateng** [comment]
In previous **Problem Formulations** notebook, after running the through the Workbench , the outcome keys are clearly distinct. 
dict_keys(['A.1 Total Costs', 'A.1_Expected Number of Deaths', 'A.2 Total Costs', 'A.2_Expected Number of Deaths', 'A.3 Total Costs', 'A.3_Expected Number of Deaths', 'A.4 Total Costs'.......])

now after running:
dict_keys(['Expected Annual Damage 0', 'Dike Investment Costs 0', 'Expected Number of Deaths 0', 'RfR Total Costs 0', 'Expected Evacuation Costs 0', 'Expected Annual Damage 1', 'Dike Investment Costs 1', 'Expected Number of Deaths 1', 'RfR Total Costs 1', 'Expected Evacuation Costs 1'.....])

Is that intended?

**Comment by EwoutH** [comment]
@eboateng Did you change the input parameter of `get_model_for_problem_formulation()` in cell 4? If you change this value you get different output values. I think 1 to 4 are valid options.

**Comment by eboateng** [comment]
I'll do that. Had 5 previously. Still had 0-5 in the notebook comment. Thanks

**Comment by quaquel** [comment]
First, a meta point. Check https://stackoverflow.com/help/how-to-ask and apply it. We both are wasting time by going back and forth trying to clarify what your exact question is. 

Even now, your question remains not clear and leaves me guessing. You refer in your first post to the last commit. This one, however, only modified the robust optimization example and thus cannot be at all related to your issue. This makes me guess that your issue is related to the fix for #5, where I modified something in the underlying model.

However, this guess is also unlikely, since the commit for fixing #5 changes things within dike_model_function.py. The modifications to Problem_Formulations.ipynb seem all be related to rerunning it and some minor code cleanup. You can check this yourself by going to the diff for a given commit.

So, I have no idea what is going on, nor have you given me enough context to replicate whatever issue you are having. My hunch, and again I have to guess because you have made no effort to be clear, is that you are comparing two different formulations of the problem. The first list of keys seem associated with a disaggregated problem formulation. The second list seems associates with a problem formulation where the objetives are aggregated over space, but not over time.

**Comment by quaquel** [comment]
@EwoutH so it seems my hunch was indeed correct. Thanks.

**Comment by eboateng** [comment]
I apoligize I overlooked the #7 commit.
